apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "azure-ai-services.fullname" . }}
  labels:
    {{- include "azure-ai-services.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "azure-ai-services.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "azure-ai-services.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "azure-ai-services.serviceAccountName" . }}
      {{- if not (or (eq .Values.kubernetesVersion "pre-1.24") (semverCompare "<1.24" .Values.kubernetesVersion)) }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{- if not (or (eq .Values.kubernetesVersion "pre-1.24") (semverCompare "<1.24" .Values.kubernetesVersion)) }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort | default .Values.service.port }}
              protocol: TCP
          env:
            - name: eula
              value: "accept"
            {{- if .Values.documentIntelligence.azure.downloadLicense }}
            - name: billing
              value: {{ .Values.documentIntelligence.azure.billingEndpoint | quote }}
            - name: apikey
              valueFrom:
                secretKeyRef:
                  name: {{ include "azure-ai-services.fullname" . }}-azure
                  key: apiKey
            - name: DownloadLicense
              value: "True"
            {{- end }}
            - name: Mounts{{ .Values.documentIntelligence.envSeparator | default "_" }}License
              value: {{ .Values.documentIntelligence.license.mountPath | quote }}
            - name: Mounts{{ .Values.documentIntelligence.envSeparator | default "_" }}Output
              value: {{ .Values.documentIntelligence.output.mountPath | quote }}
            {{- if .Values.documentIntelligence.shared.enabled }}
            - name: SharedRootFolder
              value: {{ .Values.documentIntelligence.shared.mountPath | quote }}
            - name: Mounts{{ .Values.documentIntelligence.envSeparator | default "_" }}Shared
              value: {{ .Values.documentIntelligence.shared.mountPath | quote }}
            {{- end }}
            - name: Logging.Console.LogLevel.Default
              value: {{ .Values.documentIntelligence.advanced.logging.consoleLogLevel | default "Information" | quote }}
            {{- if .Values.documentIntelligence.advanced.storageTimeToLiveInMinutes }}
            - name: StorageTimeToLiveInMinutes
              value: {{ .Values.documentIntelligence.advanced.storageTimeToLiveInMinutes | quote }}
            {{- end }}
            {{- if .Values.documentIntelligence.advanced.taskMaxRunningTimeSpanInMinutes }}
            - name: Task:MaxRunningTimeSpanInMinutes
              value: {{ .Values.documentIntelligence.advanced.taskMaxRunningTimeSpanInMinutes | quote }}
            {{- end }}
            {{- if .Values.documentIntelligence.advanced.healthCheckMemoryUpperboundInMB }}
            - name: HealthCheck:MemoryUpperboundInMB
              value: {{ .Values.documentIntelligence.advanced.healthCheckMemoryUpperboundInMB | quote }}
            {{- end }}
            {{- if .Values.documentIntelligence.advanced.queueAzureConnectionString }}
            - name: Queue:Azure:ConnectionString
              value: {{ .Values.documentIntelligence.advanced.queueAzureConnectionString | quote }}
            {{- end }}
            {{- if .Values.documentIntelligence.advanced.storageObjectStoreAzureBlobConnectionString }}
            - name: Storage:ObjectStore:AzureBlob:ConnectionString
              value: {{ .Values.documentIntelligence.advanced.storageObjectStoreAzureBlobConnectionString | quote }}
            {{- end }}
            {{- if .Values.documentIntelligence.advanced.httpProxyBypassUrls }}
            - name: HTTP_PROXY_BYPASS_URLS
              value: {{ .Values.documentIntelligence.advanced.httpProxyBypassUrls | quote }}
            {{- end }}
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: license
              mountPath: {{ .Values.documentIntelligence.license.mountPath }}
            - name: output
              mountPath: {{ .Values.documentIntelligence.output.mountPath }}
            {{- if .Values.documentIntelligence.shared.enabled }}
            - name: shared
              mountPath: {{ .Values.documentIntelligence.shared.mountPath }}
            {{- end }}
            {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
        {{- if .Values.vector.enabled }}
        - name: vector
          image: "{{ .Values.vector.image.repository }}:{{ .Values.vector.image.tag }}"
          imagePullPolicy: {{ .Values.vector.image.pullPolicy }}
          args:
            - "--config"
            - "/etc/vector/vector.toml"
          env:
            - name: HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          {{- with .Values.vector.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: output
              mountPath: /logs
              readOnly: true
            - name: vector-config
              mountPath: /etc/vector
            - name: vector-data
              mountPath: /vector-data-dir
        {{- end }}
      volumes:
        - name: license
          {{- if .Values.documentIntelligence.license.licenseData }}
          secret:
            secretName: {{ include "azure-ai-services.fullname" . }}-license
            items:
            - key: license.dat
              path: license.dat
          {{- else }}
          persistentVolumeClaim:
            claimName: {{ .Values.documentIntelligence.license.existingClaim | default (printf "%s-license" (include "azure-ai-services.fullname" .)) }}
          {{- end }}
        - name: output
          persistentVolumeClaim:
            claimName: {{ .Values.documentIntelligence.output.existingClaim | default (printf "%s-output" (include "azure-ai-services.fullname" .)) }}
        {{- if .Values.documentIntelligence.shared.enabled }}
        - name: shared
          persistentVolumeClaim:
            claimName: {{ .Values.documentIntelligence.shared.existingClaim | default (printf "%s-shared" (include "azure-ai-services.fullname" .)) }}
        {{- end }}
        {{- if .Values.vector.enabled }}
        - name: vector-config
          configMap:
            name: {{ include "azure-ai-services.fullname" . }}-vector-config
        - name: vector-data
          emptyDir: {}
        {{- end }}
        {{- with .Values.volumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
