{{- if .Values.documentIntelligence.azure.downloadLicense }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "azure-ai-services.fullname" . }}-azure
  labels:
    {{- include "azure-ai-services.labels" . | nindent 4 }}
type: Opaque
stringData:
  apiKey: {{ .Values.documentIntelligence.azure.apiKey | quote }}
{{- end }}
---
{{- if .Values.documentIntelligence.license.licenseData }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "azure-ai-services.fullname" . }}-license
  labels:
    {{- include "azure-ai-services.labels" . | nindent 4 }}
type: Opaque
data:
  license.dat: {{ .Values.documentIntelligence.license.licenseData | b64enc }}
{{- end }}
