{{- if .Values.documentIntelligence.azure.downloadLicense }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "azure-ai-services.fullname" . }}-azure
  labels:
    {{- include "azure-ai-services.labels" . | nindent 4 }}
type: Opaque
stringData:
  apiKey: {{ .Values.documentIntelligence.azure.apiKey | quote }}
{{- end }}
